In [12]:
import numpy as np 
from math import e, factorial

test = np.random.randint(1,5, size=(2,3,4,2))
test

array([[[[3, 1],
         [2, 1],
         [3, 1],
         [1, 1]],

        [[3, 1],
         [1, 3],
         [1, 2],
         [1, 3]],

        [[1, 3],
         [3, 3],
         [2, 4],
         [1, 3]]],


       [[[1, 2],
         [1, 4],
         [2, 3],
         [1, 2]],

        [[3, 4],
         [3, 3],
         [3, 2],
         [3, 3]],

        [[1, 3],
         [1, 4],
         [4, 2],
         [1, 3]]]])

In [15]:
test.flatten()

array([3, 1, 2, 1, 3, 1, 1, 1, 3, 1, 1, 3, 1, 2, 1, 3, 1, 3, 3, 3, 2, 4,
       1, 3, 1, 2, 1, 4, 2, 3, 1, 2, 3, 4, 3, 3, 3, 2, 3, 3, 1, 3, 1, 4,
       4, 2, 1, 3])

In [21]:
np.zeros((2
          ,2)).flatten()

array([0., 0., 0., 0.])

In [26]:
x = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20]]) 
x

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20]])

In [23]:
y = np.array([1,2,3])

In [24]:
y

array([1, 2, 3])

In [28]:
x = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20]]) #(3,3)
y = np.array([1, 2, 3]) #(3,)
x + y #(3,3)
x.shape

(3, 3)

In [15]:
import numpy as np
a = np.random.randint(1,10, size=(3,4))
a

array([[9, 2, 2, 4],
       [4, 4, 3, 1],
       [3, 5, 1, 9]])

In [16]:
a[0]

array([9, 2, 2, 4])

In [32]:
a = np.arange(10, 1, -1)
a.shape
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [36]:
b = a[np.array([3, 3, 1, 8,-3])]
b

array([7, 7, 9, 2, 4])

In [44]:
x = np.array([1., -1., -2., 3])
x[x < 0] +=20
x

array([ 1., 19., 18.,  3.])